### ISSUE TITLE
Chat History auto deleting

### ISSUE THREAD

**Issue by lsdaakasdlklfsaldjfooei** [Azure-Samples/azure-search-openai-demo#1873] opened 2024-07-29 22:03 UTC
Hi, Can you please help me resolve this issue when I am going from one section to another, e.g., chat and learn to ask a question or ask a question to fact check the chat history, along with developer settings, are getting deleted; please tell me me how to fix this?
I suppose it can refresh as the user clears chat or refreshes the browser; I tried solving it myself, but I faced a lot of errors as this is not my expertise. Any help will be appreciated; thank you.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Ask a question in chat
>Go to ask a question
>return to chat. The message/chat history is cleared without clicking on clear chat along with developer tools settings.

### Any log messages given by the failure
>

### Expected/desired behavior
>The chat should be there unless I refresh (chat being on local storage) or click on clear chat.
>If possible, also guide me on how I can apply this to the developer setting as the override prompt template and other settings get factory reset every time we switch from chat and learn to ask a question or vice versa.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2024-08-06 22:26
This is currently by design, there is no persistence of either chat history or settings. Here's a feature request where we discuss persistance of developer settings:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/1791
And here's a PR on a much older version of the repo that adds conversation history persistance:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/259
I hope to get that PR updated to work with the latest version of the repo sometime this month.

I'll close this issue, since we have the same requests filed elsewhere, please inquire on those threads/PRs as needed.

**Closed by pamelafox** 2024-08-06 22:26 UTC
