### ISSUE TITLE
What is the difference between AZURE_OPENAI_CHATGPT_DEPLOYMENT vs AZURE_OPENAI_GPT_DEPLOYMENT?

### ISSUE THREAD

**Issue by saisescapades** [Azure-Samples/azure-search-openai-demo#156] opened 2023-04-27 04:25 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rngadam** [comment] 2023-05-02 19:18
I also find this very confusing as it doesn't exactly map to anything in Azure OpenAI frontend. Ended up specifying only AZURE_OPENAI_GPT_DEPLOYMENT= with the name of the model deployment.

**Comment by tekowalsky** [comment] 2023-05-05 21:02
AZURE_OPENAI_CHATGPT_DEPLOYMENT is the deployment that includes the GPT 3.5 Turbo model.

AZURE_OPENAI_GPT_DEPLOYMENT is the deployment that includes the davinci model.

The code in this repository attempts to use both, in "/app/backend/approaches/chatreadretrieveread.py"
-- AZURE_OPENAI_GPT_DEPLOYMENT to "generate an optimized keyword search query based on the chat history and the last question".   
The keyword search query is used by Cognitive Search to search the documents.

-- AZURE_OPENAI_CHATGPT_DEPLOYMENT to generate the answer to the question that was asked, from the documents found by the Cognitive Search keyword search.

However, the code is written to try to use the wrong API when it uses AZURE_OPENAI_CHATGPT_DEPLOYMENT.  
The "openai.completions" api cannot be used with the GPT 3.5 Turbo model.  The "openai.chatcompletions" api must be used, instead.

see Issue 169
https://github.com/Azure-Samples/azure-search-openai-demo/issues/169

**Comment by zhongshuai-cao** [comment] 2023-05-10 02:22
> 

Hi @tekowalsky , it is valid to use the old-fashioned API call on GPT3.5 and the app is able to run as designed. But it seems we won't have official support to rewrite the chat part as nobody is assigned to the chatcompletion-related issues...

I wonder how likely they will rewrite the prompt and refactor the code to make it happen, as we seem to be on ourselves...

**Comment by pamelafox** [comment] 2023-07-12 14:04
Since the chat approach now uses chat deployment, I think the code is clearer and this can be closed.

**Closed by pamelafox** 2023-07-12 14:04 UTC
