### ISSUE TITLE
Search resource fails in swedencentral

### ISSUE THREAD

**Issue by dfberry** [Azure-Samples/azure-search-openai-demo#1575] opened 2024-05-01 17:18 UTC
for azd up, I select these locations from the list of locations:

1) azure location: sweden central
2) docIntelligence: europe
3) openAI: sweden central

these were selected from the available options

Then the search resource fails because it isn't in sweden central. Can this be fixed so that the search is separated out into the valid regions?

**Comment by pamelafox** [comment] 2024-05-07 18:42
I think the failure had to do with the semantic ranker, right? As the search service is available in Sweden Central otherwise: https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=search

@mattgotteiner @chuwik I think we considered a separate region for search service in the past but given that it's 95% available, we didn't do that, to reduce complexity. The swedencentral issue is an annoying one since that's commonly known to be a good region for GPT model deployments. The availability page says ranker wont be available there til 2025. What do you think, should we introduce another location parameter for search? If you could get ranker there sooner... ;-)

**Comment by pamelafox** [comment] 2024-10-07 22:17
Closing as duplicate of https://github.com/Azure-Samples/azure-search-openai-demo/issues/1341

**Closed by pamelafox** 2024-10-07 22:17 UTC
Labels: azd
