### ISSUE TITLE
prepdocs.py doesn't support spaces in file path

### ISSUE THREAD

**Issue by hmoazam** [Azure-Samples/azure-search-openai-demo#244] opened 2023-05-29 17:15 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Download the solution in a directory whose path contains spaces

### Any log messages given by the failure
> `Running "prepdocs.py"
usage: prepdocs.py [-h] [--category CATEGORY] [--skipblobs] [--storageaccount STORAGEACCOUNT] [--container CONTAINER] [--storagekey STORAGEKEY]
                   [--tenantid TENANTID] [--searchservice SEARCHSERVICE] [--index INDEX] [--searchkey SEARCHKEY] [--remove] [--removeall] [--localpdfparser]
                   [--formrecognizerservice FORMRECOGNIZERSERVICE] [--formrecognizerkey FORMRECOGNIZERKEY] [--verbose]
                   files
prepdocs.py: error: unrecognized arguments: - Microsoft\Documents\OpenAI\azure-search-demo/data/*`

### Expected/desired behavior
> prepdocs.py escapes any spaces in the file path

### OS and Version?
> Windows 11

### azd version?
>  1.0.1

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by EMCP** [comment] 2023-05-29 20:40
I'd say spaces in paths is bad form.. but if you want to support it submit a PR

**Comment by socullen** [comment] 2023-05-29 21:51
When working Microsoft OneDrive, the path automatically includes a space. It is {my name} - Microsoft. What workaround do you suggest @EMCP?

**Comment by EMCP** [comment] 2023-05-29 22:07
to clarify, are you loading docs from a one-drive account.. and many of the directories it creates or uses have spaces?

**Comment by socullen** [comment] 2023-05-30 07:02
I'm cloning the repo to my local computer. The OneDrive directory on my computer is called '{my name} - Microsoft', which has a space in its path.

**Comment by EMCP** [comment] 2023-05-31 10:16
> I'm cloning the repo to my local computer. The OneDrive directory on my computer is called '{my name} - Microsoft', which has a space in its path.

if it were me, I dunno if this is possible since I don't know OneDrive or your particular computer.. but I'd just copy the cloned repo out of OneDrive, as well as any data you want to work with .. if possible.  

I am assuming you cannot do this though because of the size of the local hard drive and your datasets?

**Comment by socullen** [comment] 2023-05-31 10:54
This workaround worked for me. Thank you @EMCP. However, others will run into this issue in the future without knowing the cause. To enhance UX, I would suggest fixing this issue or adding a hint in the documentation.

**Comment by hmoazam** [comment] 2023-05-31 12:38
I agree with socullen - it would be great to have a note in the readme to ensure the solution is downloaded to a file path without spaces, and/or a more apparent error message - the one I shared above is not highlighted as an error message in the console.

**Comment by EMCP** [comment] 2023-06-01 13:47
I do not work @ MSFT , but I would guess they'd welcome a PR stating what bad state you found and the workaround..?  or even patching the behavior away entirely.. I do not have a windows machine or onedrive

**Comment by pamelafox** [comment] 2023-07-18 17:27
The relevant line of code is https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/prepdocs.ps1#L39C79-L39C82 - where it uses $cwd in the call to prepdocs

I'd love a PR to patch that up. (Am not much of a Powershell writer myself since I don't have a Windows machine, but I assume it could be put in quotes or escaped)

**Comment by pamelafox** [comment] 2023-07-24 20:15
Actually, there was already a PR:

https://github.com/Azure-Samples/azure-search-openai-demo/pull/71

It is now merged, so this should no longer be an issue.

**Closed by pamelafox** 2023-07-24 20:15 UTC
