### ISSUE TITLE
suggestions for ways to give access to resources in main storage

### ISSUE THREAD

**Issue by mo-albaba** [Azure-Samples/azure-search-openai-demo#1569] opened 2024-04-30 14:25 UTC
> Please provide us with the following information:
> With Azure enforce access control set to true
I am having difficulty finding a valid way(production app) to add members to have access to the main storage, which will be files shared with everyone in the organization.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful
My members are all controlled by Entra ID tenant.
I am not sure about the steps to create a group that is connected to the main storage container access(all the files inside). 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2024-04-30 17:38
Marking this as duplicate of #1532, will ask @mattgotteiner to provide ideas there. Please subscribe to that issue.

**Closed** 2024-04-30 17:39 UTC
