### ISSUE TITLE
Azure.core.exceptions.ClientAuthenticationErro

### ISSUE THREAD

**Issue by aropenai** [Azure-Samples/azure-search-openai-demo#1711] opened 2024-06-11 17:24 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Error while deploying from Azure cloud shell

### Any log messages given by the failure
Azure.core.exceptions.ClientAuthenticationError: {"type":"consoleMessage","timestamp":data":
{"message":"\nERROR: fetching token: invalid CloudShell token API response code: 400, content: 
{\"error\":{\"code\":\"AudienceNotSupported\",\"message\":\"Audience https://search.azure.com is not a supported MSI token audience. Supported audiences: 
https://management.core.windows.net/,https://management.azure.com/,https://graph.windows.net/,https://vault.azure.net,https://datalake.azure.net/,https://outlook.office365.com/,https://graph.microsoft.com/,https://batch.core.windows.net/,https://analysis.windows.net/powerbi/api,https://storage.azure.com/,https://rest.media.azure.net,https://api.loganalytics.io,https://ossrdbms-aad.database.windows.net,https://www.yammer.com,https://digitaltwins.azure.net,0256f7db2f9b4,https://dev.azuresynapse.net,https://database.windows.net,https://quantum.microsoft.com,https://iothubs.azure.net,2f,https://azuredatabricks.net/,ce34e7e5--964f-b3d2b16d1e4f,https://azure-devices-provisioning.net,https://managedhsm.azure.net,499b84ac-1321-427f-aa17-267ca6975798,https://api.adu.microsoft.com/,https://purview.azure.net/,6dae42f8-4678-94ff-3960e28e3630,https://cognitiveservices.azure.com,48ad--b5ef-422a-88d4-2a7f9de6a0b2,https://pki.azure.net\"}}\n"}}

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.
azd version 1.9.3
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2024-06-13 05:48
Please share your experience in this issue about Cloud Shell:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/629

I will mark this as a duplicate of that.

**Closed by pamelafox** 2024-06-13 05:48 UTC
