### ISSUE TITLE
How to run in development?

### ISSUE THREAD

**Issue by miggytrinidad** [Azure-Samples/azure-search-openai-demo#657] opened 2023-09-20 14:04 UTC
Hello,

Quick question, is there anyway I can do development work without running npm run build all the time?

When I ran, npm run dev, It is not able to interact with backend.

**Comment by pamelafox** [comment] 2023-09-20 20:31
@miggytrinidad Please see my suggested workflow here:

https://github.com/Azure-Samples/azure-search-openai-demo/issues/490

I'll close this as a duplicate of that one.

**Closed by pamelafox** 2023-09-20 20:31 UTC
