### ISSUE TITLE
Secure Web App with Azure AD

### ISSUE THREAD

**Issue by anarchitect** [Azure-Samples/azure-search-openai-demo#616] opened 2023-09-09 00:14 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> follow all steps, and the app is not secured by Azure AD

### Any log messages given by the failure
>no

### Expected/desired behavior
>Is there any particular reason the website is anonymously accessible by default, otherwise I am happy to do a pull request to secure the app services with Azure AD. :-) 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here. 1.3.0

### Versions
> 1.3.0

### Mention any other details that might be useful
Is there any particular reason the website is anonymously accessible by default, otherwise I am happy to do a pull request to secure the app services with Azure AD. :-) 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
<img width="603" alt="Screenshot 2023-09-09 at 10 12 39 am" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/2878492/4b292f34-17fd-4a16-91ab-f4eb34cb7d27">

**Comment by pamelafox** [comment] 2023-09-09 04:21
We are working on automating it in https://github.com/Azure-Samples/azure-search-openai-demo/pull/534 
In the meantime, the readme contains pointers for adding AAD. Let us know if you try out that PR and have feedback.

**Comment by pamelafox** [comment] 2023-09-09 04:22
Closing this as duplicate of https://github.com/Azure-Samples/azure-search-openai-demo/issues/404

**Closed** 2023-09-09 04:27 UTC
