### ISSUE TITLE
Add support to enable Document-level access control

### ISSUE THREAD

**Issue by waelkdouh** [Azure-Samples/azure-search-openai-demo#576] opened 2023-08-31 20:10 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

It would be great to provide the option in this project to [Enable Document-level access control](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data#document-level-access-control)

**Comment by pamelafox** [comment] 2023-09-01 17:26
Thanks @waelkdouh , this is a popular request and hopefully we can find a better way to demonstrate it for this sample. Please see existing discussion in https://github.com/Azure-Samples/azure-search-openai-demo/issues/274 and https://github.com/Azure-Samples/azure-search-openai-demo/issues/214
I'll close this issue as a duplicate of #274

**Closed by pamelafox** 2023-09-01 17:26 UTC
