### ISSUE TITLE
How to run this locally with a existing resource group?

### ISSUE THREAD

**Issue by thwayant** [Azure-Samples/azure-search-openai-demo#598] opened 2023-09-06 08:01 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Hi, I am very new to this, the place where im interning has provided me with a resources group with all necessary resources and my responsibility is to do something similar to this with our data, however this entire thing is very new to me as im only an intern and have only worked on frontend stuff, so if possible can anyone please help me run this with existing resource group, i don't have authority to create new resources/resource group. Thanks and apologies if this is inappropriate.
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by felixwcf** [comment] 2023-09-06 10:33
First you need 
1. To learn python and react and their project files structure. 
2. To have .env file to include all services IDs and names parameters that point to your existing cloud resources.

**Comment by pamelafox** [comment] 2023-09-07 13:21
As mentioned in readme, your Azure Account must have Microsoft.Authorization/roleAssignments/write permissions, such as [User Access Administrator](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#user-access-administrator) or [Owner](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#owner).

You might have more success setting up the "With Your Data" app from Azure OpenAI studio, as I believe that requires less permissions.
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data

Closing this as duplicate of #4

**Closed by pamelafox** 2023-09-07 13:21 UTC

**Comment by pamelafox** [comment] 2023-09-15 18:51
Update: We've clarified on the README that at the minimum, you need the RBAC role to run `azd up`, or the RBAC role scoped to an existing resource group: https://github.com/Azure-Samples/azure-search-openai-demo#azure-account-requirements
I've also added instructions for deploying to an existing RG.

We're interested to hear if your employers are able to give you that level of access (especially resource group scoped) or if that is still high of a level of access. 

I also documented in another issue how to manually assign the roles in the Portal, but I assume that will only work if you have RBAC access for that RG:

https://github.com/Azure-Samples/azure-search-openai-demo/issues/634#issuecomment-1721699823

If you cannot be granted RBAC at the resource group level, then I think the only other approach is to use keys instead of managed identity. That should be possible with changes to the credentials in app.py. We generally discourage keys when possible, however, so we haven't yet enabled that in the repo.
