### ISSUE TITLE
How to make user uploaded files globally available to all the users using ChatApp.

### ISSUE THREAD

**Issue by lokeshkri** [Azure-Samples/azure-search-openai-demo#1567] opened 2024-04-29 19:22 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> azd version 1.8.1 (commit 88369c36ce2a0d60794389aad9b10de938f587e1)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mo-albaba** [comment] 2024-04-30 14:41
I am also interested in testing this for my project if there is a valid way to do it.

**Comment by pamelafox** [comment] 2024-04-30 17:38
Marking this as duplicate of #1532, will ask @mattgotteiner to provide ideas there.

**Closed by pamelafox** 2024-04-30 17:38 UTC
