### ISSUE TITLE
Data ingestion for big pdf not happening properly.

### ISSUE THREAD

**Issue by mrisahoo1** [Azure-Samples/azure-search-openai-demo#2126] opened 2024-11-07 11:34 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
scripts/prepdocs.ps1
### Any log messages given by the failure
>
 File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\search\documents\aio\_search_client_async.py", line 685, in _index_documents_actions
    batch_response = await self._client.documents.index(batch=batch, error_map=error_map, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\core\tracing\decorator_async.py", line 94, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\search\documents\_generated\aio\operations\_documents_operations.py", line 855, in index
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\core\exceptions.py", line 161, in map_error
    raise error
azure.search.documents._search_documents_error.RequestEntityTooLargeError: Operation returned an invalid status 'Request Entity Too Large'
Content: The page was not displayed because the request entity is too large.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WKK9OUQ\Desktop\MCo-Search\app\backend\prepdocs.py", line 426, in <module>
    loop.run_until_complete(main(ingestion_strategy, setup_index=not args.remove and not args.removeall))
  File "C:\Users\Sample_User\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Sample_User\Desktop\MCo-Search\app\backend\prepdocs.py", line 239, in main
    await strategy.run()
  File "C:\Users\Sample_User\Desktop\MCo-Search\app\backend\prepdocslib\filestrategy.py", line 90, in run
    await search_manager.update_content(sections, blob_image_embeddings, url=file.url)
  File "C:\Users\Sample_User\Desktop\MCo-Search\app\backend\prepdocslib\searchmanager.py", line 297, in update_content
    await search_client.upload_documents(documents)
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\search\documents\aio\_search_client_async.py", line 578, in upload_documents
    results = await self.index_documents(batch, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\core\tracing\decorator_async.py", line 94, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\search\documents\aio\_search_client_async.py", line 677, in index_documents
    return await self._index_documents_actions(actions=batch.actions, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\search\documents\aio\_search_client_async.py", line 691, in _index_documents_actions
    batch_response_first_half = await self._index_documents_actions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sample_User\Desktop\MCo-Search\.venv\Lib\site-packages\azure\search\documents\aio\_search_client_async.py", line 685, in _index_documents_actions
    batch_response = await self._client.documents.index(batch=batch, error_map=error_map, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'error_map'
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11
### azd version?
> run `azd version` and copy paste here.
azd version 1.10.4 
### Versions
>

### Mention any other details that might be useful
Need help with resolving this error.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2024-11-07 23:45
Can you share your file with yall@microsoft.com? They're working on reproducing issues with Document Intelligence timeouts. I'll close this as duplicate of https://github.com/Azure-Samples/azure-search-openai-demo/issues/485 which manifests in a few ways.

**Closed by pamelafox** 2024-11-07 23:45 UTC
