### ISSUE TITLE
Fix hyperlink for Learn how to switch to OpenAI instance

### ISSUE THREAD

**Issue by AjayKumar-MSFT** [Azure-Samples/azure-search-openai-demo#1039] opened 2023-12-07 02:39 UTC
### Minimal steps to reproduce
>

For [README.md](https://github.com/Azure-Samples/azure-search-openai-demo#readme)
Under: Azure account requirements : https://github.com/Azure-Samples/azure-search-openai-demo#azure-account-requirements
The Line : You can use [OpenAI public API](https://platform.openai.com/docs/api-reference/introduction) instead. **Learn [how to switch to an OpenAI instance**](https://github.com/Azure-Samples/azure-search-openai-demo#switching-from-an-azure-openai-endpoint-to-an-openai-instance).

Ask: Need to fix the URL 

The GitHub sample is referencing to this public OpenAI doc URL: https://platform.openai.com/docs/api-reference/introduction - for "Learn how to switch to OpenAI instance" - However, as it's circling back to Read.me. Need to fix the URL 

### Any log messages given by the failure
>
None
### Expected/desired behavior
>
Fix the URL in read.me

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
None

### azd version?
> run `azd version` and copy paste here.
NA

### Versions
>
NA

### Mention any other details that might be useful

Reference: Based on the feedback raised by [Siegfried Heintze](https://learn.microsoft.com/en-us/users/na/?userid=db9dda72-31e1-4b0f-b55c-d25f81371d04) on [Microsoft Q&A question](https://learn.microsoft.com/en-us/answers/questions/1457235/how-to-run-openai-demo-with-openai-instead-of-azur). 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2023-12-07 04:20
I've sent a PR here: https://github.com/Azure-Samples/azure-search-openai-demo/pull/1035

**Comment by pamelafox** [comment] 2023-12-07 05:18
Closing as dupe of https://github.com/Azure-Samples/azure-search-openai-demo/issues/1033

**Closed** 2023-12-07 05:18 UTC
