### ISSUE TITLE
Failure to launch locally (openAI token)

### ISSUE THREAD

**Issue by hermanhaavik** [Azure-Samples/azure-search-openai-demo#438] opened 2023-07-19 14:10 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
 azd env refresh -e "env-name"
 az ad signed-in-user show --query id -o tsv -> then gets the id here and pastes it in the .env file as AZURE_PRINCIPAL_ID
 cd app &&  ./start.ps1

### Any log messages given by the failure
>Starting backend

Incomplete environment configuration. These variables are set: AZURE_TENANT_ID
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.

### Expected/desired behavior
>
Excpects the application to run and connect the backend to the frontend, seems to be that the backend wont start for now(when running locally)

### OS and Version?
> Windows 11

### azd version?
> 1.1.0

### Versions
> Python 3.11.4 (team member also runs the same, it works there)

### Mention any other details that might be useful
It works for equivlant machines/setuos
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2023-07-19 23:43
Could you avoid pasting PRINCIPAL_ID in the .env file? I think that's confusing it, since it sees the .env file and thinks it should get authentication details from there. However, it should get the authentication locally from the azd credential, from `azd auth login`. I suggest removing the .env file, running `azd auth login`, and seeing if that works. Let us know how it goes.

**Comment by hermanhaavik** [comment] 2023-07-20 06:38
Now it works, thanks a lot. Heard from colleagues that it was needed as they have it in their .env file. But anyway, thanks for the help!

**Comment by hermanhaavik** [comment] 2023-07-20 06:38
Now it works, thanks a lot. Heard from colleagues that it was needed as they have it in their .env file. But anyway, thanks for the help!

**Comment by pamelafox** [comment] 2023-07-20 10:04
Can you paste the error you're seeing?

**Comment by hermanhaavik** [comment] 2023-07-20 10:35
Starting backend

Incomplete environment configuration. These variables are set: AZURE_TENANT_ID
Obtaining key... (Custom print statement used for finding where it stops, lcoated inn app.py)
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
        ManagedIdentityCredential: Unexpected content type "text/html"
Content: <html><head><title>504 Gateway Timeout</title></head>
<body><h1>Gateway Timeout</h1>
<p>Server error - server 169.254.169.254 is unreachable at this moment.<br><br>Please retry the request or contact your administrator.<br></p>
</body></html>

To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Traceback (most recent call last):
  File "C:\Users\AD09800\Desktop\tmt\app\backend\app.py", line 43, in <module>
    openai_token = azure_credential.get_token("https://cognitiveservices.azure.com/.default")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AD09800\Desktop\tmt\app\backend\backend_env\Lib\site-packages\azure\identity\_credentials\default.py", line 214, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AD09800\Desktop\tmt\app\backend\backend_env\Lib\site-packages\azure\identity\_credentials\chained.py", line 111, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
        ManagedIdentityCredential: Unexpected content type "text/html"
Content: <html><head><title>504 Gateway Timeout</title></head>
<body><h1>Gateway Timeout</h1>
<p>Server error - server 169.254.169.254 is unreachable at this moment.<br><br>Please retry the request or contact your administrator.<br></p>
</body></html>

To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
PS C:\Users\AD09800\Desktop\tmt\app\backend>

**Comment by hermanhaavik** [comment] 2023-07-24 09:06
Yeah, my machine is using a VPN as part of the company policy, but its configured the same as the rest of the teams so  I dont believe that to be the root of the problem?

**Comment by pamelafox** [comment] 2023-07-24 16:42
I'm not sure why your machine is experiencing a Gateway Timeout there, if its not being caused by the VPN. You could open a new issue in the Azure Python SDK repo to see if they have additional ideas: https://github.com/Azure/azure-sdk-for-python/

It's also possible that your teammates machines aren't seeing the issue as they might have other credentials setup that are being found before it attempts to ping the Managed Identity Azure IP. 

Did you try this change?

azure_credential = DefaultAzureCredential(exclude_managed_identity_credential=True)

**Comment by hermanhaavik** [comment] 2023-07-25 11:33
Ill take a look at the SDK repo, azure_credential = DefaultAzureCredential(exclude_managed_identity_credential=True) had no effect unfortunately

**Comment by pamelafox** [comment] 2023-07-25 12:53
Can you share the error after changing to that? It should at least be different since it shouldnt be attempting to check for a managed identity credential.

**Comment by hermanhaavik** [comment] 2023-07-26 12:15
Okay, we are getting somewhere, now it works, the version of the repo we worked on didnt have any parameters inside    azure_credential = DefaultAzureCredential() but with both of them it runs. Thanks! Do you have any tips on how I could implement an automatic check to see if its local or not, and from there set the value to true or false? Again thanks for the help!

**Comment by pamelafox** [comment] 2023-07-26 12:45
Great! Here's a common way I check for production for App Service apps:

```
if 'WEBSITE_HOSTNAME' in os.environ: # production

else: # development

```

App Service always sets WEBSITE_HOSTNAME on a deployed app, so as long as you don't set that env variable locally, that check should work.

**Comment by pamelafox** [comment] 2023-08-22 03:57
Closing since I think we found an approach for your environment.

**Closed by pamelafox** 2023-08-22 03:57 UTC
