### ISSUE TITLE
User Engagement Report

### ISSUE THREAD

**Issue by mo-albaba** [Azure-Samples/azure-search-openai-demo#2130] opened 2024-11-08 06:14 UTC
I have the repo deployed in my environment with authentication enabled. I'd like to know if there’s a way to generate a report that shows who is sending requests and actively using the application.

Could you please help me find a way to gather a user engagement report?

Thank you!

**Comment by mo-albaba** [comment] 2024-11-19 05:59
Hi @pamelafox, Yes it is the same request and I am getting the same result as @Mahmoud-Hesham99 while having Authentication enabled and knowing that hundreds of users use the app daily.
![image](https://github.com/user-attachments/assets/2d6a5e1e-c723-4156-a01c-6f7fbaf64dd5)

**Comment by pamelafox** [comment] 2024-11-21 17:25
Closing this as duplicate of #1714

**Closed** 2024-11-21 17:25 UTC
