### ISSUE TITLE
Adapting the web app for mobile devices

### ISSUE THREAD

**Issue by poonkuzhali** [Azure-Samples/azure-search-openai-demo#1809] opened 2024-07-12 13:27 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>  Has anyone tried to make the web app adaptable to a mobile device? I am not very familiar with how to do it. Any guidance will be 
 hugely appreciated.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2024-07-12 19:45
Yes, @zedhaque is working on it. Have you tried the latest release? https://github.com/Azure-Samples/azure-search-openai-demo/releases/tag/2024-07-10
I think Zed has a few other improvements in mind, see:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/1458

I'll close this as a duplicate of that. Please continue conversation there with your feedback.

**Closed by pamelafox** 2024-07-12 19:45 UTC
