### ISSUE TITLE
Better parsing of result like in ChatGPT it gives in markdown format and it formatted beautifully.

### ISSUE THREAD

**Issue by UsamaMoinJavid** [Azure-Samples/azure-search-openai-demo#882] opened 2023-10-30 13:49 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
![image](https://github.com/Azure-Samples/azure-search-openai-demo/assets/61883188/5a551013-d118-4f18-b6de-0f9c166613d6)

### Expected/desired behavior
> the result should be in table form

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2023-10-30 16:11
This PR accomplishes that:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/56

I have used that in a branch and it worked fairly well, though it can be a little jarring with streaming, since it tries to HTMLify partially streamed Markdown.

**Comment by pamelafox** [comment] 2023-10-30 16:12
Marking this as duplicate of #30

**Closed by pamelafox** 2023-10-30 16:12 UTC
