### ISSUE TITLE
Jump to the right page

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/azure-search-openai-demo#1245] opened 2024-02-07 07:36 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------
Hello,

Following the recent update, upon clicking the PDF file reference link, the file displayed started from the very first file page instead of the referenced one as worked previously. Anyone observing the same thing?

Thanks!

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Linux

### azd version?
> run `azd version` and copy paste here.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment] 2024-02-07 19:38
Which browser do you see that in? I see it sometimes in Edge, and I reported the issue to the Edge team. I haven't seen it in Chrome.

**Comment by mirojs** [comment] 2024-02-08 04:37
@pamelafox I mainly use Chrome and it worked before but not until most recently following the update. Testing on Edge told the same story.

**Comment by amreales** [comment] 2024-02-11 18:34
Seeing the same issue. Tested on Edge, Chrome and Safari, reference document opening in page 1 regardless of the anchor

**Comment by Adeelku** [comment] 2024-02-16 21:45
The same issue here,  I am using Edge

**Comment by pamelafox** [comment] 2024-02-16 22:39
Ah, I see the issue, this was introduced when we added GPT-4-v support. Working on a fix. Sorry for the delay!

**Comment by pamelafox** [comment] 2024-02-16 23:04
Actually this regression was caused by https://github.com/Azure-Samples/azure-search-openai-demo/pull/1160/files#r1460470297

Still working on a fix

**Comment by pamelafox** [comment] 2024-02-17 00:03
Fix is in review. Necessary changes are in one file:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1283/files#diff-1c152a9cc611df2db331cd06ae6145ca33249071c2e6c4cf1ae02cb0ea7b8970

**Closed** 2024-02-17 00:05 UTC
